### ISSUE TITLE
Trouble with the getting started example

### ISSUE THREAD

**Issue by bartbunting** [sowderca/connectwise-ruby-sdk#2]
I am trying to connect to our connectwise instance using the example code.

There is nothing in the example about how to set the hostname.
Also how to set the companyId 
Checked  configuration.rb and tried hostname.

I am used to using an api_key, set that also with no luck.

Would it be possible to provide an example of how to access the api using an api key and setting the hostname?

It would be even more wonderful if you could show an example of how to get list of service  tickets for example.

When I try by setting host, username, password I get:

ruby t.rb
Exception when calling AccountingBatchesApi->finance_accounting_batches_count_get: URL using bad/illegal format or missing URL

t.rb looks like:

require 'connectwise-ruby-sdk'

# Setup authorization
ConnectWise.configure do |config|
  # Configure HTTP basic authorization: BasicAuth
  config.host = 'api-aus.myconnectwise.net'
  config.username = 'xxxx
  config.password = 'xxxxx'
end

api_instance = ConnectWise::AccountingBatchesApi.new

opts = {
  conditions: "conditions_example" # String |
}

begin
  result = api_instance.finance_accounting_batches_count_get(opts)
  p result
rescue ConnectWise::ApiError => e
  puts "Exception when calling AccountingBatchesApi->finance_accounting_batches_count_get: #{e}"
end

One more thing:
When I enabled debugging I get the following error:

ruby t.rb
/Users/bart/.rvm/gems/ruby-2.1.4/gems/connectwise-ruby-sdk-2.0.0/lib/connectwise-ruby-sdk/api/accounting_batches_api.rb:29:in `finance_accounting_batches_count_get_with_http_info': undefined method `debug' for nil:NilClass (NoMethodError)
	from /Users/bart/.rvm/gems/ruby-2.1.4/gems/connectwise-ruby-sdk-2.0.0/lib/connectwise-ruby-sdk/api/accounting_batches_api.rb:18:in `finance_accounting_batches_count_get'
	from t.rb:19:in `<main>'

Thanks for any help you can provide.

**Comment by sowderca** [comment]
Hey @bartbunting, 

Sorry for the confusion, I believe I forgot to update the documentation with the latest release. Try using the following:

```ruby
 ConnectWise.configure do |config|
    config.username = "#{company_id}+#{public_api_key}"
    config.password =  "#{private_api_key}"
    config.host = 'api-aus.myconnectwise.net' # your connectwise url
    config.base_path = '/v4_6_release/apis/3.0' # Or alternative code base release
    config.scheme = 'https'
  end
```

**Comment by bartbunting** [comment]
Wonderful, that works.

The only remaining issue is how do I enable debug?

```ruby

api_instance.config.logger.debug("test")
``` 
Throws an error:

t.rb:21:in `<main>': undefined method `config' for #<ConnectWise::AccountingBatchesApi:0x007fd3089129a8> (NoMethodError)

I'm sure I'm missing something here.

**Comment by sowderca** [comment]
It *should* default to using the stdlib logger unless you are using Rails, but I was able to reproduce your error on my machine. I believe I have a fix which I will push an update for. 

Until then you can override the logger option to allow for debugging:

```ruby
require 'logger'

 ConnectWise.configure do |config|
    config.username = "#{company_id}+#{public_api_key}"
    config.password =  "#{private_api_key}"
    config.host = 'api-aus.myconnectwise.net' # your connectwise url
    config.base_path = '/v4_6_release/apis/3.0' # Or alternative code base release
    config.scheme = 'https'
    config.debugging = true
    config.logger = Logger.new(STDOUT)
  end
```

Or using a 3rd party logging lib such as fluent:
```ruby
require 'fluent-logger'

 ConnectWise.configure do |config|
    config.username = "#{company_id}+#{public_api_key}"
    config.password =  "#{private_api_key}"
    config.host = 'api-aus.myconnectwise.net' # your connectwise url
    config.base_path = '/v4_6_release/apis/3.0' # Or alternative code base release
    config.scheme = 'https'
    config.debugging = true
    config.logger = Fluent::Logger::LevelFluentLogger.new('fluent')
  end
```

**Comment by sowderca** [comment]
@bartbunting were you able to resolve the issue?

**Comment by bartbunting** [comment]
Cameron,

Thanks very much.  Yes that worked fine.

Sorry had not had  a chance to test it.

Thanks for your help!

Kind regards

Bart
